title: MemoTrack - docs
theme: just-the-docs
baseurl: ""

just_the_docs:
  heading_levels: 2..4
  collections:
    usermanual:
      output: true
      permalink: /usermanual/:path/
      sort_order: automatic  
      toc: true   
