title: MemoTrack - docs
theme: just-the-docs
baseurl: ""
repository: Memo-Track/docs
just_the_docs:
  permalink: pretty
  heading_levels: 2..4
  collections:
    usermanual:
      output: true
      permalink: /usermanual/:path/
      sort_order: automatic
